apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA1rze6fRmUtwYFViLBJudmZiuGZXgUEb28DBYkuV16GIjdyk4lMY930d4WJG/fGFKHXV1lqLZR2GKzMwhvK12HatZhUqAuHzu8uiA5bDuamiS1wOPrGloFIk954JE/8F8fEtLP+ufSIvp4zPeIHO36+rUt9x6msR/w4QPHiP7JBjKmBUCBnJTcgl7WNb0PntYkasEXbbdUe7KAFFPocpA5AmNRJdx8dxmKBrnMq7iX83eDTr0iXc/0lSD77S1YSzYZquKpz5PD4SAxukTHs87LEIGBV4xby5yQED02LEF4P+9wM5rGhsigSuaVZ4FKvvt2lw4Z7nPzE2bzfUaXSDmcnIAQuXibokoBPGVeFbSH4BCjMfXG6R1uSJMRWmn46bViFYilbXOXmt/EFv43eoypNR0MZcSJY4Qme6k+xlGAZcqO85RXg1bMtSwg8o/DWFnG1aBjOg24MPcClTqq6n7XS33JLkjLu9sV8V2sh7/H8hgU5lc1/IXW9pc4CWZnBS7ipjNsnPZ3PSS0i7J+sTmRmPeLHh/Dw6d9MAH2VxnU6RWBsE8UnbNQb7I0uhoWN1awtiQS7lERRYhxonzPwFD83v+qXye3uraEAi89OoSkJ6OA4uVygRkR46e+DOIQ9XGxN4C+dKLrxVQTFLcDiJWrS6Jyel65ftUR8JUE+OqsYsHMelBEnuCdeipMCbA9EP0LYpNgMV6wCNYVisNR2DSM1oXqEvoNeuHAwYIzrQkGb7ETBv01OGtT
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

